version: '3.8'

services:
  ffc-sfi-processing-web:
    build:
      context: .
      target: production
    image: ffc-sfi-processing-web
    container_name: ffc-sfi-processing-web
    depends_on:
      - ffc-sfi-processing-web-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-sfi-processing-web-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      SUBMIT_TOPIC_ADDRESS: ${SUBMIT_TOPIC_ADDRESS:-ffc-sfi-agreement-submit}${MESSAGE_QUEUE_SUFFIX}
      SUBMIT_SUBSCRIPTION_ADDRESS: ${SUBMIT_SUBSCRIPTION_ADDRESS:-ffc-sfi-agreement-submit-processing}${MESSAGE_QUEUE_SUFFIX}
      CASE_TOPIC_ADDRESS: ${CASE_TOPIC_ADDRESS:-ffc-sfi-agreement-case}${MESSAGE_QUEUE_SUFFIX}
      CASE_SUBSCRIPTION_ADDRESS: ${CASE_SUBSCRIPTION_ADDRESS:-ffc-sfi-agreement-case-processing}${MESSAGE_QUEUE_SUFFIX}
      PAYMENT_TOPIC_ADDRESS: ${PAYMENT_TOPIC_ADDRESS:-ffc-pay-request}${MESSAGE_QUEUE_SUFFIX}
      VALIDATE_TOPIC_ADDRESS: ${VALIDATE_TOPIC_ADDRESS:-ffc-sfi-agreement-validate}${MESSAGE_QUEUE_SUFFIX}
      VALIDATION_TOPIC_ADDRESS: ${VALIDATION_TOPIC_ADDRESS:-ffc-sfi-agreement-validate-response}${MESSAGE_QUEUE_SUFFIX}
      VALIDATION_SUBSCRIPTION_ADDRESS: ${VALIDATION_SUBSCRIPTION_ADDRESS:-ffc-sfi-agreement-validate-response-processing}${MESSAGE_QUEUE_SUFFIX}
      CRMCASE_TOPIC_ADDRESS: ${CRMCASE_TOPIC_ADDRESS:-ffc-sfi-crm-case}${MESSAGE_QUEUE_SUFFIX}
      CLOSECRMCASE_TOPIC_ADDRESS: ${CLOSECRMCASE_TOPIC_ADDRESS:-ffc-sfi-crm-close}${MESSAGE_QUEUE_SUFFIX}
      CLOSECRMCASE_SUBSCRIPTION_ADDRESS: ${CLOSECRMCASE_SUBSCRIPTION_ADDRESS:-ffc-sfi-crm-close-processing}${MESSAGE_QUEUE_SUFFIX}
      POSTGRES_DB: ffc_sfi_processing_web
      POSTGRES_HOST: ${POSTGRES_HOST:-ffc-sfi-processing-web-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ppp}
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
      POSTGRES_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}

  ffc-sfi-processing-web-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ffc_sfi_processing_web
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
