version: '3.8'

services:
  ffc-sfi-processing-web:
    build:
      context: .
      target: production
    image: ffc-sfi-processing-web
    container_name: ffc-sfi-processing-web
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-sfi-processing-web-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST:-notset}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD:-notset}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER:-notset}
      SUBMIT_TOPIC_ADDRESS: ${SUBMIT_TOPIC_ADDRESS:-notset}
      SUBMIT_SUBSCRIPTION_ADDRESS: ${SUBMIT_SUBSCRIPTION_ADDRESS:-notset}
      CASE_TOPIC_ADDRESS: ${CASE_TOPIC_ADDRESS:-notset}
      CASE_SUBSCRIPTION_ADDRESS: ${CASE_SUBSCRIPTION_ADDRESS:-notset}
      PAYMENT_TOPIC_ADDRESS: ${PAYMENT_TOPIC_ADDRESS:-notset}
      VALIDATE_TOPIC_ADDRESS: ${VALIDATE_TOPIC_ADDRESS:-notset}
      VALIDATION_TOPIC_ADDRESS: ${VALIDATION_TOPIC_ADDRESS:-notset}
      VALIDATION_SUBSCRIPTION_ADDRESS: ${VALIDATION_SUBSCRIPTION_ADDRESS:-notset}
