version: '3.8'

# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-sfi-processing-web:
    build:
      target: development
    image: ffc-sfi-processing-web-development
    container_name: ffc-sfi-processing-web-development
    ports:
      - "3006:3006"
      - "9236:9229"
    volumes:
      - ./app/:/home/node/app/
      - ./package.json:/home/node/package.json

  ffc-sfi-processing-web-postgres:
    ports:
      - "5437:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
