version: '3.8'

services:
  ffc-sfi-processing-web:
    build:
      context: .
      target: production
    image: ffc-sfi-processing-web
    container_name: ffc-sfi-processing-web
    depends_on:
      - ffc-sfi-processing-web-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-sfi-processing-web-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST:-notset}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD:-notset}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER:-notset}
      SUBMIT_TOPIC_ADDRESS: ${SUBMIT_TOPIC_ADDRESS:-notset}
      SUBMIT_SUBSCRIPTION_ADDRESS: ${SUBMIT_SUBSCRIPTION_ADDRESS:-notset}
      CASE_TOPIC_ADDRESS: ${CASE_TOPIC_ADDRESS:-notset}
      CASE_SUBSCRIPTION_ADDRESS: ${CASE_SUBSCRIPTION_ADDRESS:-notset}
      PAYMENT_TOPIC_ADDRESS: ${PAYMENT_TOPIC_ADDRESS:-notset}
      VALIDATE_TOPIC_ADDRESS: ${VALIDATE_TOPIC_ADDRESS:-notset}
      VALIDATION_TOPIC_ADDRESS: ${VALIDATION_TOPIC_ADDRESS:-notset}
      VALIDATION_SUBSCRIPTION_ADDRESS: ${VALIDATION_SUBSCRIPTION_ADDRESS:-notset}
      CRMCASE_TOPIC_ADDRESS: ${CRMCASE_TOPIC_ADDRESS:-notset}
      CLOSECRMCASE_TOPIC_ADDRESS: ${CLOSECRMCASE_TOPIC_ADDRESS:-notset}
      CLOSECRMCASE_SUBSCRIPTION_ADDRESS: ${CLOSECRMCASE_SUBSCRIPTION_ADDRESS:-notset}
      APPINSIGHTS_CLOUDROLE: ffc-sfi-processing-web-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      POSTGRES_DB: ffc_sfi_processing_web
      POSTGRES_HOST: ${POSTGRES_HOST:-ffc-sfi-processing-web-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ppp}
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
      POSTGRES_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}

  ffc-sfi-processing-web-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ffc_sfi_processing_web
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
