{{- include "ffc-helm-library.container-config-map" (list . "ffc-sfi-processing-web.config-map") -}}
{{- define "ffc-sfi-processing-web.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  {{- if .Values.container.googleTagManagerKey }}
  GOOGLE_TAG_MANAGER_KEY: {{ quote .Values.container.googleTagManagerKey }}
  MESSAGE_QUEUE_HOST: {{ quote .Values.container.messageQueueHost }}
  SUBMIT_TOPIC_ADDRESS: {{ quote .Values.container.submitTopicAddress }}
  SUBMIT_SUBSCRIPTION_ADDRESS: {{ quote .Values.container.submitSubscriptionAddress }}
  CASE_TOPIC_ADDRESS: {{ quote .Values.container.caseTopicAddress }}
  CASE_SUBSCRIPTION_ADDRESS: {{ quote .Values.container.caseSubscriptionAddress }}
  PAYMENT_TOPIC_ADDRESS: {{ quote .Values.container.paymentTopicAddress }}
  VALIDATE_TOPIC_ADDRESS: {{ quote .Values.container.validateTopicAddress }}
  VALIDATION_TOPIC_ADDRESS: {{ quote .Values.container.validationTopicAddress }}
  VALIDATION_SUBSCRIPTION_ADDRESS: {{ quote .Values.container.validationSubscriptionAddress }}
  {{- end }}
{{- end -}}
