environment: development
name: ffc-sfi-processing-web
namespace: ffc-sfi
workstream: ffc-sfi
image: ffc-sfi-processing-web

labels:
  component: web

appInsights:
  key:

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID

containerConfigMap:
  name: ffc-sfi-processing-web-config-map

containerSecret:
  name: ffc-sfi-processing-web-container-secret
  type: Opaque

service:
  port: 80
  type: ClusterIP

deployment:
  restartPolicy: Always
  priorityClassName: default
  replicas: 1
  minReadySeconds: 0

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 10Mi
  requestCpu: 10m
  limitMemory: 120Mi
  limitCpu: 120m
  port: 3006
  messageQueueHost: namespace.servicebus.windows.net
  submitTopicAddress: ffc-sfi-agreement-submit
  submitSubscriptionAddress: ffc-sfi-agreement-submit-processing
  caseTopicAddress: ffc-sfi-agreement-case
  caseSubscriptionAddress: ffc-sfi-agreement-case-processing
  paymentTopicAddress: ffc-sfi-payment-request
  validateTopicAddress: ffc-sfi-agreement-validate
  validationTopicAddress: ffc-sfi-agreement-validate-response
  validationSubscriptionAddress: ffc-sfi-agreement-validate-response-processing

ingress:
  class: nginx
  endpoint: ffc-sfi-processing-web
  server: example.com

livenessProbe:
  path: /healthz
  port: 3006
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3006
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

aadPodIdentity: true
