environment: development
name: ffc-sfi-processing-web
namespace: ffc-sfi
workstream: ffc-sfi
image: ffc-sfi-processing-web

labels:
  component: web

appInsights:
  key:

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID

containerConfigMap:
  name: ffc-sfi-processing-web-config-map

containerSecret:
  name: ffc-sfi-processing-web-container-secret
  type: Opaque

service:
  port: 80
  type: ClusterIP

deployment:
  restartPolicy: Always
  priorityClassName: default
  replicas: 1
  minReplicas: 2
  maxReplicas: 4
  cpuThreshold: 80
  memoryThreshold: 80
  minReadySeconds: 0

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 180Mi
  requestCpu: 40m
  limitMemory: 250Mi
  limitCpu: 120m
  port: 3006
  messageQueueHost: namespace.servicebus.windows.net
  submitTopicAddress: ffc-sfi-agreement-submit
  submitSubscriptionAddress: ffc-sfi-agreement-submit-processing
  caseTopicAddress: ffc-sfi-agreement-case
  caseSubscriptionAddress: ffc-sfi-agreement-case-processing
  paymentTopicAddress: ffc-sfi-payment-request
  validateTopicAddress: ffc-sfi-agreement-validate
  validationTopicAddress: ffc-sfi-agreement-validate-response
  validationSubscriptionAddress: ffc-sfi-agreement-validate-response-processing
  crmCaseTopicAddress: ffc-sfi-crm-case-create
  closeCrmCaseTopicAddress: ffc-sfi-crm-case-closed
  closeCrmCaseSubscriptionAddress: ffc-sfi-crm-case-closed-processing'

ingress:
  class: nginx
  endpoint: ffc-sfi-processing-web
  server: example.com
  
postgresService:
  postgresDb: ffc_sfi_processing_web
  # postgresExternalName is the external host name to which PostgreSQL
  # requests should be forwarded. If empty, PostgreSQL is assumed to be
  # within the cluster and accessible via postgresHost
  postgresExternalName:
  postgresHost: ffc-sfi-processing-web-postgres
  postgresPort: 5432
  postgresSchema: public
  postgresUser: postgres

livenessProbe:
  path: /healthz
  port: 3006
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3006
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

aadPodIdentity: true
